name: Create Release

on:
  workflow_dispatch:
    inputs:
      release-number:
        description: 'Release number'
        required: true
      release-title:
        description: 'Release title'
        required: false

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  call-create-release:
    uses: milosz-barylowicz/cpp-projects-github-actions/.github/workflows/create-release.yml@v1.0.2
    with:
      release-version: ${{ inputs.release-number }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
