name: Delete Outdated Workflows Runs

on:
  schedule:
  - cron:  '0 3 * * SUN'
  workflow_dispatch:

jobs:
  call-delte-outdated-workflows-run:
    uses: milosz-barylowicz/cpp-projects-github-actions/.github/workflows/delete-outdated-workflow-runs.yml@v1.0.2
