name: docker-build

on:
  pull_request:
    branches: [ 'main' ]

  schedule:
    - cron:  '0 3 * * SUN'
  workflow_dispatch:

jobs:
  build:
    runs-on: [ 'ubuntu-24.04' ]

    steps:
    - uses: actions/checkout@v6.0.1
    - uses: milosz-barylowicz/cpp-projects-github-actions/python3-upgrade@v1.0.2
      with:
        python3-version: '15'
        operating-system: 'ubuntu-24.04'

    - name: python-venv-setting-up
      run: |
        python3.15 -m venv venv && \
        source venv/bin/activate && \
        newgrp docker

    - name: docker-container-configuration-and-execution
      working-directory: ${{ github.workspace }}
      run: |
        python scripts/docker/build_and_run.py --user $(id -u) --group $(id -g)
